name: Heroku Awake

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/15 23,0-17 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://labs.smilecat.dev/"